### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by gabeins** [mebibou/mdl-selectfield#1]
Not everyone uses bower, and, with the rise in the use of npm as a dependency manager for font-end packages, I believe the community would benefit a great deal from this package being available there.

**Comment by mebibou** [comment]
published: https://www.npmjs.com/package/mdl-selectfield

**Comment by gabeins** [comment]
Awesome! Thanks!

What do you think about removing the [hardcoded path to `bower_components`](https://github.com/mebibou/mdl-selectfield/blob/master/src/selectfield/selectfield.scss#L1-L2) inside the Sass file? It will cause issues when building form the source using Sass.

Personally, I think the Material variables and mixins should be expected to be on the scope already, but I'm not sure how you would go about building it for the processed version of the file without the reference.

**Comment by mebibou** [comment]
@gabrielizaias you are welcome to do a pull-request if you have another solution :)
