### ISSUE TITLE
Add ability to use disabled options in select field.

### ISSUE THREAD

**Issue by SergeiStruk** [mebibou/mdl-selectfield#11]
Please, add support for disabled options. Example: http://www.w3schools.com/tags/att_option_disabled.asp

**Comment by mebibou** [comment]
Could you explain what kind of "support" you are looking for? if you just add `disabled="disabled"` it will behave like a disabled option

**Comment by SergeiStruk** [comment]
Yes, it should just behalf like a disabled option, i.e. when user clicks on disabled option 1) value of select should not be changed 2) drop down should not be closed

Also disabled options should be gray.

**Comment by mebibou** [comment]
Could you tell me what doesn't work on the plugin? I don't see what there is to be done here, the element is still a `<select>` element and behaves as such

**Comment by SergeiStruk** [comment]
Options with `disabled="disabled"` don't behave like disabled, you can choose them, which is incorrect. You can test it here: http://codepen.io/anon/pen/ZWzxaj

**Comment by mebibou** [comment]
@SergeiStruk this is not my plugin that you are using, so you should probably log the issue on the right github.

An example with disabled using a fork of the example on my homepage: http://codepen.io/mebibou/pen/NNKLoJ
