### ISSUE TITLE
Border bottom not aligned with the other text fields

### ISSUE THREAD

**Issue by GianlucaGuarini** [mebibou/mdl-selectfield#12]
The border bottom of the select fields have 1px less of the default material input fields on firefox and ie.
I have attached the screenshot of the issue

Firefox 46.0a2
![screen shot 1](https://cloud.githubusercontent.com/assets/879612/13349551/fe7ea6c0-dc7a-11e5-9a4f-3e999caa5149.png)

IE10
![screen shot](https://cloud.githubusercontent.com/assets/879612/13349553/ffd5cc10-dc7a-11e5-9885-ac0f04a1c81c.png)

Here you can check a demo of the issue http://codepen.io/GianlucaGuarini/pen/eZOoeO

I have tried many css fixes but I can not figure out how to solve this problem any help is really appreciated

**Comment by mebibou** [comment]
If you set a fixed height on the `input` and `select` to be the same, then they will be aligned. On Firefox, setting `height: 30px;` on the `<select class="mdl-selectfield__select"/>` element will make them both aligned. Since the `material-design-lite` doesn't set fixed height, and that the height is different on different navigators, you'll have to set them yourself

**Comment by GianlucaGuarini** [comment]
Setting the `height:30px` aligns the select on firefox but it will not be aligned on chrome and safari. I have updated the example http://codepen.io/GianlucaGuarini/pen/eZOoeO Probably you need to set the height dynamically via javascript

**Comment by mebibou** [comment]
Even if you set the height on both the `select` and `input`?

**Comment by GianlucaGuarini** [comment]
nope http://codepen.io/GianlucaGuarini/pen/eZOoeO

**Comment by mebibou** [comment]
try to add `box-sizing: border-box; -moz-box-sizing: border-box;` on both elements

**Comment by GianlucaGuarini** [comment]
It didn't work. Maybe it's simply not possible. You can fork my example trying to figure out whether there could be a workaround. I have tried also flexbox but with no success. Thanks anyway

**Comment by mebibou** [comment]
That looks like a bug of Firefox then, because both elements have exactly the same dimensions and attributes, sorry mate
