### ISSUE TITLE
respect current color palette

### ISSUE THREAD

**Issue by digitalkaoz** [mebibou/mdl-selectfield#16]
currently the library doenst respect the choosen color palette (uses the default). it would be great if this library can respect that. this extra library can handle it https://github.com/puranjayjain/md-date-time-picker maybe you can get some inspiration from their solution

**Comment by mebibou** [comment]
yeah I know it's been reported before in #13, but the solution of [md-date-time-picker](https://github.com/puranjayjain/md-date-time-picker) is not a good one imo because he's copying the files from mdl into his library, so he will need to manually update after every release...
Would setting a `$mdl-path` in the `scss` file for you to override it may work? you would only need to do:

```
$mdl-path: './bower_components/mdl';
@import './bower_components/mdl-selectfield/src/selectfield/selectfield.scss';
```

**Comment by digitalkaoz** [comment]
mh ive seen you have some hard dependeny on bower, im using npm only here...

what whould a `$mdl-path` change?

**Comment by mebibou** [comment]
by setting it before calling the `scss` file you could set your own path for the mdl library.

**Comment by digitalkaoz** [comment]
mh yes this might work, so the hard dependency on bower would be removed?

``` scss
@import "../../bower_components/material-design-lite/src/variables";
@import "../../bower_components/material-design-lite/src/mixins";
```

**Comment by mebibou** [comment]
yes this would be transformed to:

```
$mdl-path: '../../bower_components/material-design-lite' !default;
@import "$mdl-path/src/variables",
  "$mdl-path/src/mixins";
```

I haven't tested it but this should work

**Comment by digitalkaoz** [comment]
but im already doing it this way:

``` js
import 'material-design-lite/dist/material.light_green-green.min.css'
import 'material-design-lite/material';
import 'mdl-selectfield/src/selectfield/selectfield';
import 'mdl-selectfield/src/selectfield/selectfield.scss';
```

i modified your scss:

``` scss
@import "~material-design-lite/src/variables";
@import "~material-design-lite/src/mixins";
```

but its still blue and not green

**Comment by digitalkaoz** [comment]
i guess its a problem of mixing `dist css` and `src scss`...anyway, the `$mdl-path` would be a good change anyway!

**Comment by mebibou** [comment]
I am missing a lot of info on what you are doing, but shouldn't you add color classes to the select field instead? I though you changed some scss variables that were not picked up
