### ISSUE TITLE
Error in mdl-selectfield.js

### ISSUE THREAD

**Issue by ghost** [mebibou/mdl-selectfield#19]
Just noticed one, tiny error preventing the labels from working correctly. 

```
  MaterialSelectfield.prototype.CssClasses_ = {
    LABEL: 'mdl-selectield__label',
    SELECT: 'mdl-selectfield__select',
    IS_DIRTY: 'is-dirty',
    IS_FOCUSED: 'is-focused',
    IS_DISABLED: 'is-disabled',
    IS_INVALID: 'is-invalid',
    IS_UPGRADED: 'is-upgraded'
  };
```

The label class is listed as `mdl-selectield__label` instead of `mdl-selectfield__label`.

Thanks for the script though, it's much appreciated! :)

**Comment by mebibou** [comment]
Should be fixed in `1.0.2`
