### ISSUE TITLE
How to set default value?

### ISSUE THREAD

**Issue by ningliu** [mebibou/mdl-selectfield#20]
I tried both to add value="option1" on either the outermost "div" tag or the "select" tag.  Neither works.  Please advise.
Adding "selected" on the "option" is not recommended.

**Comment by mebibou** [comment]
I am not sure I understand what you are asking. On any `<select></select>` element, default value is set using `<option selected="selected"></option>`. What are you trying to do?

**Comment by ningliu** [comment]
I am writing a React wrapper for this component.  React will generate a warning if using selected="selected".  But I think I can ignore the warning and still do the adding "selected" on the "option" way.

**Comment by mebibou** [comment]
Well if something wrong then it's because of your react component, the only way in html is to use the attribute on the option, so nothing I could do here.
