### ISSUE TITLE
What is the best way to get the current selected value?

### ISSUE THREAD

**Issue by ningliu** [mebibou/mdl-selectfield#21]
I am writing a React wrapper for this. 
I am trying to add "onchange" event on the "select" tag, and try to get the newly selected value.  Thanks!

**Comment by mebibou** [comment]
This library provides a pure javascript way to handle a select field, using the official mdl library. It is not a forum to ask question on how to write React components. Please ask all non-related to this library question on stackoverflow or something, thanks.
