### ISSUE TITLE
Uncaught ReferenceError: componentHandler is not defined

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [mebibou/mdl-selectfield#24]
Hi,

I was getting an error "Uncaught ReferenceError: componentHandler is not defined". When I moved 
`componentHandler.register({
      constructor: MaterialSelectfield,
      classAsString: 'MaterialSelectfield',
      cssClass: 'mdl-js-selectfield',
      widget: true
    });`

to

`$(document).ready(function($) {
    componentHandler.register({
      constructor: MaterialSelectfield,
      classAsString: 'MaterialSelectfield',
      cssClass: 'mdl-js-selectfield',
      widget: true
    });   
  });` 

It is working fine

Thanks,
Unnikrishnan B.

**Comment by mebibou** [comment]
Please check existing issues reported before posting a new issue => https://github.com/mebibou/mdl-selectfield/issues/14
