### ISSUE TITLE
Error state doesn't work properly if initialized with is-invalid class

### ISSUE THREAD

**Issue by tddrmllr** [mebibou/mdl-selectfield#25]
If the `mdl-selectfield` div has the `is-invalid` class when the page is loaded, the label is quickly removed and the error state does not display. This is problematic if a form is re-rendered in order to display error messages to the user. The native MDL input components do not have this behavior.

To replicate, simply add the `is-invalid` class to the "with floating label" [codepen](http://codepen.io/mebibou/pen/pjEjOv) example provided in the readme, and watch the preview pane. You'll see it re-initialize with the proper styles, but then quickly (almost imperceptibly) revert back.

I've tried several ways to fix this, but haven't found the solution yet.

**Comment by mebibou** [comment]
So you couldn't find the answer in the native component's code right? I haven't updated the code based on the native one, I should do that when I find the time, maybe it would fix the issue you are having

**Comment by tddrmllr** [comment]
No. I dug in a little bit, though not too in depth, to see if I could find differences in how objects were behaving, but nothing jumped out to me.

**Comment by mh-cbon** [comment]
Hi,

Same issue here. ~~I dig the source, i m thinking to add a condition post-init to test if the `is-invalid` class is present to set `this.select_.validity.valid = false` .~~ (validity is an html5 new thing with read only properties, valid is one of those)

~~I m unsure if this is the right way to do it.~~

~~I d really like a feedback to sort this out in way or another.~~

~~thanks!~~

---

Given core mdl class TextField, in the init func

``` js
  MaterialSelectfield.prototype.init = function() {
// ...
        var invalid = this.element_.classList
          .contains(this.CssClasses_.IS_INVALID);
        this.updateClasses_();
        this.element_.classList.add(this.CssClasses_.IS_UPGRADED);
        if (invalid) {
          this.element_.classList.add(this.CssClasses_.IS_INVALID);
        }
// ...
  }
```
