### ISSUE TITLE
MDL 1.2? 

### ISSUE THREAD

**Issue by ghost** [mebibou/mdl-selectfield#27]
Will mdl-selectfield work with MDL 1.2? Trying to update lists 1.1.3 as a dependency, which means the 1.2.1 update fails. Is there any reason why this wouldn't work with 1.2? 

Thanks!

**Comment by russell-tarpley** [comment]
I've been using mdl-selectfield with MDL 1.2 in my application for the last 2 weeks and haven't ran into issues as of yet.

**Comment by ghost** [comment]
Great! It didn't look like anything major was done in 1.2 but I just wanted to make sure there wasn't a reason for it to be locked to 1.1. :)

**Comment by mebibou** [comment]
I'll close this as it doesn't seem like you are logging an issue at all. Thanks
