### ISSUE TITLE
Add mdl as dependency

### ISSUE THREAD

**Issue by davidpelayo** [mebibou/mdl-selectfield#3]
I would rather go for adding the [mtd dependency](https://github.com/google/material-design-lite) in the project and require only the select input javascript. This way you don't need to maintain manually the select input from mtd manually.

What do you think?

**Comment by mebibou** [comment]
@davidpelayo I'm not sure I understand what you mean

**Comment by davidpelayo** [comment]
Never mind. I misunderstood something at the time I was writing it.
