### ISSUE TITLE
componentHandler

### ISSUE THREAD

**Issue by radzev1ch** [mebibou/mdl-selectfield#33]
Hi! upgradeElement does not work on  selectfield node.

**Comment by mebibou** [comment]
Could you be a bit more descriptive? thanks

**Comment by jaseyd** [comment]
I have the same problem. mdl-selectfield no longer works with the update of MDL (1.3.0). 
See [Codepen](http://codepen.io/anon/pen/wJJpQq)
Console error: 
Uncaught ReferenceError: componentHandler is not defined
    at selectfield.js:196
    at selectfield.js:200

UPDATE: It didn't seem to like me linking to your file through codepen. [Here ](http://codepen.io/anon/pen/qrrxRZ)is a version with the JS inserted directly

**Comment by jaseyd** [comment]
Meh, it was just a case of removing **defer** from
<script defer src="https://code.getmdl.io/1.3.0/material.min.js">

Apologies for wasting time.

**Comment by mebibou** [comment]
yes, same as #24 and #14...
