### ISSUE TITLE
Refresh after adding more option elements

### ISSUE THREAD

**Issue by igaln** [mebibou/mdl-selectfield#36]
What would be the best approach to refresh the ui of the select after adding more <option> elements lets say via jquery?

  $(selector)
      .append('<option value="'+ value +'">'+ key + '</option>')

if I dynamically add new values onLoad. the html is updated but it is not rendered by mdl-selectfield

**Comment by mebibou** [comment]
I think you should be able to do this using the `componentHandler`. Maybe `componentHandler.upgradeAllRegistered` ? I guess this is more an issue related to material design itself, as other components would have the same problem
