### ISSUE TITLE
Merge with MDL Lite?

### ISSUE THREAD

**Issue by cweill** [mebibou/mdl-selectfield#5]
This is a great component and works really well with mdl-lite (at least on desktop when I tested it). Any chance you will open a pull request to merge it with the mdl-lite core?

**Comment by mebibou** [comment]
there is already a PR done on this kind of component, which is more likely to pass than this one, but is actually going a different way: https://github.com/google/material-design-lite/pull/1391

so either you can use [the fork](https://github.com/langan/material-design-lite) or you can keep using this component
