### ISSUE TITLE
'is-dirty' class not being added to parent on value being selected

### ISSUE THREAD

**Issue by shutupflanders** [mebibou/mdl-selectfield#6]
The floating label is not being kept floated if a value is chosen, this is due to the 'is-dirty' class missing from the wrapping <div>

Adding something similar to the jQuery code below will sort the problem:

``` javascript
$(".mdl-selectfield__select").on('change', function(){
      if($(this).val()>""){
        $(this).parent().addClass('is-dirty');
      }
      else{
        $(this).parent().removeClass('is-dirty');  
      }
    });
```

**Comment by mebibou** [comment]
could you provide a codepen or something to show what your problem is? because `is-dirty` is being added when a value is selected, and removed when there is no value selected, so maybe this is more a browser issue?

**Comment by mebibou** [comment]
@shutupflanders could you try with version 0.0.3?

**Comment by mebibou** [comment]
ok I'll close this for now, please reopen if version 0.0.3 doesn't fix
