### ISSUE TITLE
Labels on Firefox

### ISSUE THREAD

**Issue by Sparticuz** [mebibou/mdl-selectfield#7]
The labels don't quite work properly on FF (38ESR) Not sure if they work in newer versions, will test later.

![image](https://cloud.githubusercontent.com/assets/161913/11379389/2753082c-92be-11e5-8002-71f668b7477a.png)

**Comment by mebibou** [comment]
tested on latest firefox and it doesn't work indeed

**Comment by mebibou** [comment]
closed via [d7e328ab6d5354ccde1a7b81b260effbdcbfa86d](https://github.com/mebibou/mdl-selectfield/commit/d7e328ab6d5354ccde1a7b81b260effbdcbfa86d)
