### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by Sparticuz** [mebibou/mdl-selectfield#8]
Missed the v in the tag and it's not getting picked up by npm. Thanks for the quick fix on #7!

**Comment by mebibou** [comment]
well spotted ;)

**Comment by mgol** [comment]
npm still has only 0.0.2 from over 2 months ago. Tagging has nothing to do with npm, you need to `npm publish`.

**Comment by mebibou** [comment]
@mzgol oh yeah I use mainly bower and always forget to do npm, thanks
